apiVersion: v1
kind: Service
metadata:
  name: lb-eureka
  labels:
    app: eureka
spec:
  clusterIP: None
  selector:
    app: eureka
  ports:
    - protocol: TCP
      targetPort: 8761
      port: 8761
  type: NodePort
