apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  clusterIP: None
  selector:
    app: eureka
  ports:
    - protocol: TCP
      port: 8761
      name: eureka
  type: ClusterIP
