spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://mysql:3306/ingredientdb
  data:
    redis:
      host: redis
      port: 6379
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/