spring:
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
  datasource:
    username: root
    password: password
    url: jdbc:mysql://127.0.0.1:3306/supportdb
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: 127.0.0.1:19092
management:
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
sonnetto:
  urls:
    user-service: http://127.0.0.1/8081/api/v1.0/users