spring:
  ai:
    ollama:
      base-url: http://ollama:11434
  datasource:
    username: root
    password: password
    url: jdbc:mysql://mysql:3306/supportdb
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: broker:19092
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
sonnetto:
  urls:
    user-service: http://user-service/8081/api/v1.0/users