eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  security:
    user: eureka
    password: eureka
management:
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411