apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      name: notification-service
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: w4t3rcs/sonnetto-notification-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
              protocol: TCP
          envFrom:
            - configMapRef:
                name: cloud-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: NodePort