apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      name: order-service
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: w4t3rcs/sonnetto-order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
              protocol: TCP
          envFrom:
            - configMapRef:
                name: cloud-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: NodePort