server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/w4t3rcs/sonnettopizza
          search-paths: config-server/src/main/resources/configs
          clone-on-start: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka/