apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
spec:
  count: 1
  elasticsearchRefs:
    - name: elasticsearch
      clusterName: eck
  version: 8.15.0
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
        
        output {
          elasticsearch {
            hosts => [ "http://elasticsearch-es-http:9200" ]
            user => "elastic"
            password => "elastic"
            index => "sonnetto-logs"
          }
        }
  services:
    - name: beats
      service:
        spec:
          type: NodePort
          ports:
            - protocol: TCP
              port: 5044
              targetPort: 5044
              name: filebeat