apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.54.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-config
      restartPolicy: Always
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    scrape_configs:
      - job_name: 'eureka_server'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'eureka-server:8761' ]
            labels:
              application: 'Eureka Server Application'
      - job_name: 'config_server'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'config-server:8888' ]
            labels:
              application: 'Config Server Application'
      - job_name: 'user_service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'user-service:8081' ]
            labels:
              application: 'User Service Application'
      - job_name: 'ingredient_service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'ingredient-service:8082' ]
            labels:
              application: 'Ingredient Service Application'
      - job_name: 'product_service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'product-service:8083' ]
            labels:
              application: 'Product Service Application'
      - job_name: 'order_service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'order-service:8084' ]
            labels:
              application: 'Order Service Application'
      - job_name: 'notification_service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'notification-service:8085' ]
            labels:
              application: 'Notification Service Application'
      - job_name: 'api_gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'api-gateway:8080' ]
            labels:
              application: 'Api Gateway Application'