apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      name: zipkin
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:3.4.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9411
              protocol: TCP
          envFrom:
            - configMapRef:
                name: zipkin
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  selector:
    app: zipkin
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zipkin
data:
  STORAGE_TYPE: "mem"
